version: '3'
services:
  api:
    image: mahesh/todos-api
    build: .
    networks:
      - backend
    ports:
      - "3600:3600"
    depends_on:
      - mongo
      
  mongo:
    image: mongo
    container_name: mongodb    
    volumes:
      - ./data:/data/db
    networks:
      - backend
    ports:
      - "27017:27017"

  web-cli:
    image: mahesh/todos-api
    links:
      - mongo
    networks:
      - backend
    command: sh    

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    volumes:
      - ./data:/data/db
    depends_on:
      - mongo
    networks:
      - backend
    ports:
      - 8081:8081    
    networks:
      - backend     
  
networks:
  backend:
    driver: bridge